server:
  port: 8088

spring:
  datasource:
#    url: jdbc:mysql://175.178.187.5:3306/camunda?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    url: jdbc:mysql://127.0.0.1:3306/local_demo?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    password: Zyuan123
    password: 123456
  data:
    mongodb:
      uri: "mongodb://localhost:27017/test"
  redis:
    enabled: true
    timeout: 5000
#    lettuce:
#      pool:
#        # 连接池最大连接数（为负则没有限制）
#        max-active: 5000
#        # 连接池最大阻塞等待时间（为负则没有限制）
#        max-wait: -1
#        # 连接池中最大空闲连接
#        max-idle: 30
#        # 连接池中最小空闲连接
#        min-idle: 5
#    database: 0
#    host: 175.178.187.5
    host: 127.0.0.1
    port: 6379
#    password: zy123456
#    password: 123456
#    extra:
#      expire: 10
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #虚拟host 初始的就为/
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 5
    publisher-returns: true
    template:
      mandatory: true
    connection-timeout: 2000

# camunda 登录信息设置
camunda.bpm:
  admin-user:
    id: admin
    password: 123456
  database:
    type: mysql
    schema-update: true
  auto-deployment-enabled: false # 自动部署resources下的bpmn文件

es:
  first-host: 127.0.0.1
  first-port: 9200
  username: elastic
  password: zy123456
  charset: utf-8
  scheme: http
  client:
    connectTimeOut: 5000
    socketTimeOut: 15000

mybatis:
  type-aliases-package: com.zyuan.boot.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

